# Generated by Django 3.1 on 2020-08-22 11:24
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_uuids(apps, schema_editor):
    car_statuses = {
        "dostępny": settings.CAR_STATUS_AVAILABLE,
        "wypożyczony": settings.CAR_STATUS_RENT
    }

    db_alias = schema_editor.connection.alias
    CarStatus = apps.get_model("car", "CarStatus")

    for status_name, status_uuid in car_statuses.items():
        cs = CarStatus.objects.using(db_alias).get(name=status_name)
        cs.uuid = status_uuid
        cs.save()


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstatus',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars',
                                    to='car.carstatus'),
        ),
        migrations.RunPython(add_uuids)
    ]
