# Generated by Django 3.1 on 2020-08-22 11:47

import django.db.models.deletion
from django.db import migrations, models


def migrate_names(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    CarBrand = apps.get_model("car", "CarBrand")
    CarModel = apps.get_model("car", "CarModel")
    Car = apps.get_model("car", "Car")

    for car in Car.objects.using(db_alias).all():
        car_brand = CarBrand.objects.using(db_alias).get_or_create(name=car.brand_name)[0]
        car_model = CarModel.objects.using(db_alias).get_or_create(name=car.model_name, car_brand=car_brand)[0]
        car.brand, car.model = car_brand, car_model
        car.save()


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0002_auto_20200822_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models',
                                                to='car.carbrand')),
            ],
        ),
        migrations.RenameField(model_name='car', old_name='brand', new_name='brand_name'),
        migrations.RenameField(model_name='car', old_name='model', new_name='model_name'),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', null=True,
                                    to='car.carbrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', null=True,
                                    to='car.carmodel'),
        ),
        migrations.RunPython(migrate_names),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars',
                                    to='car.carbrand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars',
                                    to='car.carmodel'),
        ),
        migrations.RemoveField(model_name="car", name="brand_name"),
        migrations.RemoveField(model_name="car", name="model_name"),
    ]
